"""product shipment field

Revision ID: 3d6e446c3a38
Revises: 3867a2ca7aa9
Create Date: 2021-08-09 10:26:44.198650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6e446c3a38'
down_revision = '3867a2ca7aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('shipment', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'shipment')
    # ### end Alembic commands ###
