"""categora produto

Revision ID: 72a7108a4263
Revises: ed53f844cc61
Create Date: 2021-09-01 11:36:46.623710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a7108a4263'
down_revision = 'ed53f844cc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('main_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['main_category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'main_category')
    # ### end Alembic commands ###
