"""empty message

Revision ID: 7de3a273a47d
Revises: 3c3b84d056e5
Create Date: 2021-08-06 14:21:45.774519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de3a273a47d'
down_revision = '3c3b84d056e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_inventory')
    op.add_column('product', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'stock')
    op.create_table('product_inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_inventory_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_inventory_pkey')
    )
    # ### end Alembic commands ###
