"""estoque, itens reservados

Revision ID: d3794c633cdc
Revises: 7de3a273a47d
Create Date: 2021-08-06 16:31:33.312853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3794c633cdc'
down_revision = '7de3a273a47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('reserved', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'reserved')
    # ### end Alembic commands ###
