"""total de produtos já vendidos

Revision ID: fc173f122eae
Revises: 3d6e446c3a38
Create Date: 2021-08-09 17:04:11.989797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc173f122eae'
down_revision = '3d6e446c3a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'total')
    # ### end Alembic commands ###
